name: "Configure Google Docker"
description: "Configure Google Docker Credential helper"
author: "GarnerCorp"
branding:
  icon: "sliders"
  color: "blue"
inputs:
  container-registries:
    description: "Container Registries (space delimited)"
    required: false
  images:
    description: "Image URLs (space delimited)"
    required: false
  workload-identity-provider:
    description: "The workload identity provider to use for docker (requires service-account)"
    required: false
  service-account:
    description: "The service account to use for docker (requires workload-identity-provider)"
    required: false
  

runs:
  using: "composite"
  steps:
    - name: Validate inputs
      if: ${{ !inputs.workload-identity-provider != !inputs.service-account }}
      shell: bash
      env:
        INPUTS: ${{ toJSON(inputs) }}
        CODEPENDENT: '[ [ "workload-identity-provider", "service-account" ] ]'
      run: |
        "$GITHUB_ACTION_PATH/../scripts/report-missing-inputs.pl"

    - name: Authenticate to Google Cloud
      if: ${{ inputs.workload-identity-provider && inputs.service-account }}
      id: auth-work-identity
      uses: google-github-actions/auth@v3
      with:
        workload_identity_provider: ${{ inputs.workload-identity-provider }}
        service_account: ${{ inputs.service-account }}
    
    - name: Add google registries
      shell: bash
      if: ${{ inputs.container-registries || inputs.images }}
      env:
        registries: >-
          ${{ inputs.container-registries }}
          ${{ inputs.images }}
      run: |
        : Configure docker gcloud credential helpers if they are not already configured
        "$GITHUB_ACTION_PATH/../scripts/gcloud-auth-configure-docker.sh"
