name: 'Install package manager'
description: 'Install package manager (similar to what corepack does; but use a GitHub cached version if available)'
author: 'GarnerCorp'
branding:
  icon: 'archive'
  color: 'black'
inputs:
  cache-repository:
    description: "GitHub repository with cached packages as tags"
    required: false
  working-directory:
    description: "Working directory"
    required: false

runs:
  using: 'composite'
  steps:

    - name: Check for jq
      id: jq
      shell: bash
      run: |
        : Check for jq
        if ! which jq; then
          echo "needed=1" >> "$GITHUB_OUTPUT"
        fi

    - name: Install jq
      if: ${{ steps.jq.outputs.needed }}
      id: install-jq
      uses: check-spelling/gh-program-downloader@c6f28a25b2cbfd91693af602ed712328f4e97552 # v0.0.4 + 1 commit
      with:
        repository: jqlang/jq
        destination: ../bin/jq
        add-to-path: 1

    - name: Install package manager
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      env:
        CACHE_DIRECTORY: .cache/node/corepack/v1
        CACHE_REPOSITORY: ${{ inputs.cache-repository || format('{0}/../{1}', github.action_repository || github.repository, 'corepack-pkg-manager-cache') }}
      run: |
        : Get package manager
        if [ -n "$TRACE" ]; then
          set -x
        fi
        npm install -g corepack
        versioned_package_manager=$(jq -r '.packageManager' package.json)
        if [ -n "$versioned_package_manager" ]; then
          cache_directory=$(
            cd;
            mkdir -p "$CACHE_DIRECTORY"
            cd "$CACHE_DIRECTORY"
            pwd
          )
          (
            cd $(mktemp -d)
            url="https://github.com/$CACHE_REPOSITORY/archive/refs/tags/${versioned_package_manager}.tar.gz"
            if curl -s -S -f -L -o cached.tar.gz "$url"; then
              echo "Downloaded package manager from $url"
              tar zxf cached.tar.gz
              rm cached.tar.gz
              cd */
              mv * "$cache_directory"
            else
              echo "::notice title=Install package manager::could not download $url"
            fi
          )
        fi
        package_manager=${versioned_package_manager%@*}
        "$package_manager" install
