name: 'Test image'
description: 'Trigger image tests'
author: 'GarnerCorp'
branding:
  icon: 'upload-cloud'
  color: 'orange'
inputs:
  checkout:
    description: Whether or not to checkout the repository you are currently working in
    required: false
    default: "true"
  repository:
    description: Repository containing test information
    required: true
  ssh-key:
    description: SSH key (with write permissions) to clone repository
    required: true
  working-directory:
    description: Path within the repository managing tests
    default: .
    required: false
  name:
    description: Username to use for git commit
    required: true
  mail:
    description: Email address to use for git commit
    required: true
  project-pretty:
    description: Project name for commit message
    required: false
  default-branch:
    description: Default branch
    default: master
    required: false
  needs-json:
    description: "Jobs to check"
    required: false

runs:
  using: 'composite'
  steps:
    - name: Validate inputs
      if: ${{ !inputs.repository || !inputs.ssh-key || !inputs.name || !inputs.mail }}
      shell: bash
      env:
        INPUTS: ${{ toJSON(inputs) }}
      run: |
        "$GITHUB_ACTION_PATH/../scripts/report-missing-inputs.pl"
    - name: Validate needs
      if: ${{ inputs.needs-json }}
      uses: garnercorp/build-actions/needs@main
      with:
        needs-json: ${{ inputs.needs-json }}
    - name: Prepare for E2E Deployment
      if: (inputs.checkout == 'true') && (env.BRANCH == env.DEFAULT_BRANCH || github.event.pull_request)
      env:
        BRANCH: ${{ github.head_ref || github.ref_name }}
        DEFAULT_BRANCH: ${{ inputs.default-branch }}
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ssh-key: ${{ inputs.ssh-key }}
    - name: Ensure working directory
      shell: bash
      env:
        working_dir: ${{ inputs.working-directory }}
      run: |
        mkdir -p "$working_dir"
    - name: Trigger E2E
      shell: bash
      if: env.BRANCH == env.DEFAULT_BRANCH || github.event.pull_request
      env:
        GIT_NAME: ${{ inputs.name }}
        GIT_MAIL: ${{ inputs.mail }}
        PROJECT_PRETTY: ${{ inputs.project-pretty }}
        HEAD_SHA: ${{ github.event.pull_request.head.sha || github.sha }}
        COMMIT_URL: ${{ github.event.head_commit.url }}
        PR_REPO_URL: ${{ github.event.pull_request.head.repo.html_url }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        BRANCH: ${{ github.head_ref || github.ref_name }}
        DEFAULT_BRANCH: ${{ inputs.default-branch }}
      working-directory: ${{ inputs.working-directory }}
      run: |
        "$GITHUB_ACTION_PATH/commit-latest-versions.sh"
