#!/bin/sh
for dir in $(
  for target in $(
    find . -mindepth 2 -maxdepth 2 -name target
  ); do
    find $target -mindepth 1 -maxdepth 1 -name 'scala-*'
  done
); do
  find $dir -mindepth 1 -type f -name '*_*-*.*'
done
